"""add description to video

Revision ID: a8f90bb4a54d
Revises: 9b1ba8b694e3
Create Date: 2025-04-22 16:19:35.285446+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f90bb4a54d'
down_revision: Union[str, None] = '9b1ba8b694e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'description')
    # ### end Alembic commands ### 