"""add transcription field

Revision ID: 3bfe0575dc77
Revises: a8f90bb4a54d
Create Date: 2025-04-23 08:14:02.940854+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bfe0575dc77'
down_revision: Union[str, None] = 'a8f90bb4a54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('transcription', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'transcription')
    # ### end Alembic commands ### 